name: Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Generate code
        run: make gen

      - name: Run tests
        run: make test

      - name: Run vet
        run: go vet ./...

      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2023.1.7"

  acceptance-test:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Generate code
        run: make gen

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run acceptance tests
        run: make testacc
        env:
          TF_ACC: "1"

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Generate code
        run: make gen

      - name: Build
        run: go build -v ./...

      - name: Install
        run: make install

  docs:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Generate code
        run: make gen

      - name: Generate docs
        run: make terradocs

      - name: Check for doc changes
        run: |
          if [[ -n $(git status --porcelain docs/) ]]; then
            echo "Documentation is out of date. Please run 'make terradocs' and commit the changes."
            git status --porcelain docs/
            exit 1
          fi
