name: Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Download dependencies
        run: nix develop --command go mod download

      - name: Generate code
        run: nix develop --command make gen

      - name: Run tests
        run: nix develop --command make test

      - name: Run vet
        run: nix develop --command go vet ./...

      - name: Run staticcheck
        run: nix develop --command staticcheck ./...

  acceptance-test:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Download dependencies
        run: nix develop --command go mod download

      - name: Generate code
        run: nix develop --command make gen

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run acceptance tests
        run: nix develop --command make testacc
        env:
          TF_ACC: "1"

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Download dependencies
        run: nix develop --command go mod download

      - name: Generate code
        run: nix develop --command make gen

      - name: Build
        run: nix develop --command go build -v ./...

      - name: Install
        run: nix develop --command make install

  docs:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Download dependencies
        run: nix develop --command go mod download

      - name: Generate code
        run: nix develop --command make gen

      - name: Generate docs
        run: nix develop --command make terradocs

      - name: Check for doc changes
        run: |
          if [[ -n $(git status --porcelain docs/) ]]; then
            echo "Documentation is out of date. Please run 'make terradocs' and commit the changes."
            git status --porcelain docs/
            exit 1
          fi
